---
# .lintinel.yml
# This config file needs to be placed in the root directory of
# the repo that you wish to use Lintinel on.

rules:
  YAMLLinter: true
  BashLinter: true
  TerraformModuleVersioning: true
  DockerfileBestPractices: true
  MissingDotfiles: true
  PythonLinter: true

ai:
  enabled: true
  provider: openai
  model: gpt-4
  fixes: true
  tone: mentor  # or strict, friendly, playful
