---
# .lintinel.yml
# This config file needs to be placed in the root directory of
# the repo that you wish to use Lintinel on.

rules:
  YAMLLinter: true
  BashLinter: true
  TerraformModuleVersioning: true
  DockerfileBestPractices: true
  MissingDotfiles: true
  PythonLinter: true

ai:
  enabled: true
  provider: openai
  model: gpt-4
  fixes: true
  tone: strict  # or strict, friendly, playful

git:
  pr_diff_only: true
  base_ref: "origin/main"   # Optional; default to 'main'
