# .lintinel.yml

rules:
  YAMLLinter: true
  BashLinter: true
  TerraformModuleVersioning: true
  DockerfileBestPractices: true
  MissingDotfiles: true

ai:
  enabled: true
  provider: openai
  model: gpt-4
  tone: mentor  # or strict, friendly, playful


